{
    "name": "Web",
    "version": "1.0",
    "category": "Hidden",
    "description": "Web client core module.",
    "depends": ["base", "bus"],
    "data": [
        "views/webclient_templates.xml",
    ],
    "assets": {
        "web.assets_web": [
            "web/static/src/scss/webclient.css",
            "web/static/src/services/rpc.js",
            "web/static/src/services/session.js",
            "bus/static/src/bus_service.js",
            "web/static/src/services/action.js",
            "web/static/src/services/i18n.js",
            "web/static/src/services/registry.js",
            "web/static/src/services/views.js",
            "web/static/src/views/list_renderer.js",
            "web/static/src/views/form_renderer.js",
            "web/static/src/views/modifier_eval.js",
            "web/static/src/views/kanban_renderer.js",
            "web/static/src/components/card.js",
            "web/static/src/components/button.js",
            "web/static/src/components/badge.js",
            "web/static/src/components/avatar.js",
            "web/static/src/components/kpi_card.js",
            "web/static/src/components/activity_feed.js",
            "web/static/src/components/shortcuts_bar.js",
            "web/static/src/components/recent_items.js",
            "web/static/src/components/settings_field.js",
            "web/static/src/components/settings_table.js",
            "web/static/src/components/settings_section.js",
            "web/static/src/core/settings.js",
            "web/static/src/core/dashboard.js",
            "web/static/src/main.js",
            "web/static/src/chat_panel.js",
        ],
    },
    "installable": True,
    "auto_install": True,
}
