from . import ir_dashboard
from . import ir_translation
from . import ir_filters
from . import res_users
from . import res_partner
from . import res_country
from . import res_country_state
from . import res_currency
from . import res_currency_rate
from . import res_lang
from . import res_company
from . import res_groups
from . import res_users_apikeys
from . import ir_cron
from . import ir_sequence
from . import ir_attachment
from . import ir_model
from . import ir_model_fields
from . import ir_model_data
from . import ir_config_parameter
from . import ir_actions
from . import ir_actions_server
from . import ir_webhook
from . import ir_rule
from . import ir_module_module
from . import ir_ui_view
from . import ir_ui_menu
from . import transient_vacuum
from . import base_autovacuum
from . import base_field_test
from . import wizard_confirm
from . import db_backup
from . import approval_rule
from . import approval_request
from . import audit_log
from . import ir_dashboard_layout
