from . import mail_activity_type
from . import mail_message
from . import mail_template
from . import mail_thread
from . import mail_activity
from . import mail_mail
from . import ir_mail_server
from . import ir_actions_server
from . import ir_attachment
from . import mail_channel
from . import mail_channel_member
from . import mail_notification
from . import fetchmail_server
